### ISSUE TITLE
Fatal error : Class 'WP_Bootstrap_Navwalker' not found in "http:// header.php" on line 54

### ISSUE THREAD

**Issue by alsultant** [wp-bootstrap/wp-bootstrap-navwalker#310]
hello,
i can't access the wp_boostrap_navwlker it seem result not found on php..
thank you

**Comment by pattonwebz** [comment]
Hey @alsultant, 

It sounds like you followed instructions from the github pages branch which are in need of updating. This comment details the solution for you: https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/278#issuecomment-326141497

Essentially the filename was changed at one point and is now named `wp-bootstrap-navwalker.php` (with dashes '`-`' and not underscores '`_`').

**Comment by alsultant** [comment]
if i change the '_' to '-' this will be the result..
Fatal error
: Call to undefined function Navwalker() in
header.php
on line
54

**Comment by alsultant** [comment]
what is the best function php code for nav walker?
im still didnt active my menus on appearance..


<?php

 // Register Custom Navigation Walker
 require_once('wp_bootstrap_navwalker.php');

// Add theme support to bootstrap navigation
function tam_theme_setup()
{
    register_nav_menus(array(
        'primary' => __('Primary Menu')
        ));
}
add_action('after_setup_theme', 'tam_theme_setup');

that my code but didnt work

**Comment by pattonwebz** [comment]
@alsultant, sorry I took so long to reply here. When I said to change the name of the file I should have been clearer. I meant to change the name of the file '''at the point where you include/require it'''. 

The new error of `Call to undefined function Navwalker()` suggests you updated the call in the `wp_nav_menu` function. That should remain as `new WP_Bootstrap_Navwalker` as that is still the name of the class added by the walker, however the filename used to include the walker file was changed to `wp-bootstrap-navwalker`.

Find the call where you include the file (probably in your `functions.php` file) and update it to the new name.

**Comment by pattonwebz** [comment]
With no activity in a long time I'm closing this issue. If it's still a problem for you feel free to reopen it or to create a fresh issue for your problem.

**Comment by baggarw1** [comment]
Hi, 

I am having the same issue and have taken steps mentioned here. 

All bootstrap/jquery files have been included. Using underscores starter theme.

A little background on the setup I have:

In functions.php : 

require_once('wp-bootstrap-navwalker.php');

register_nav_menus( array(
	'primary' => __( 'Primary Menu', 'gsm' ),
) );

In header.php

<nav class="navbar navbar-expand-md navbar-light bg-light" role="navigation">
  <div class="container">
    
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<a class="navbar-brand" href="#">Navbar</a>
        <?php
        wp_nav_menu( array(
            'menu'              => 'primary',
            'theme_location'    => 'primary',
            'depth'             => 2,
            'container'         => 'div',
            'container_class'   => 'collapse navbar-collapse',
            'container_id'      => 'bs-example-navbar-collapse-1',
            'menu_class'        => 'nav navbar-nav',
            'fallback_cb'       => 'WP_Bootstrap_Navwalker::fallback',
            'walker'            => new WP_Bootstrap_Navwalker()
		) );
        ?>
    </div>
</nav>

Basically used all the standard code from the repo step by step. But in the end still getting an error on:

Navbar

Fatal error
: Uncaught Error: Class 'WP_Bootstrap_Navwalker' not found in /var/www/sport.countzero.xyz/wp-content/themes/gsm/header.php:60 Stack trace: #0 /var/www/sport.countzero.xyz/wp-includes/template.php(688): require_once() #1 /var/www/sport.countzero.xyz/wp-includes/template.php(647): load_template('/var/www/sport....', true) #2 /var/www/sport.countzero.xyz/wp-includes/general-template.php(41): locate_template(Array, true) #3 /var/www/sport.countzero.xyz/wp-content/themes/gsm/page.php(15): get_header() #4 /var/www/sport.countzero.xyz/wp-includes/template-loader.php(74): include('/var/www/sport....') #5 /var/www/sport.countzero.xyz/wp-blog-header.php(19): require_once('/var/www/sport....') #6 /var/www/sport.countzero.xyz/index.php(17): require('/var/www/sport....') #7 {main} thrown in
/var/www/sport.countzero.xyz/wp-content/themes/gsm/header.php
on line
60

Still need a solution.

Thanks

**Comment by pattonwebz** [comment]
Hey @baggarw1, which version of the navwalker are you using? The latest from the master branch? Latest is 4.0.1.

Version 4 onwards was a big rewrite. During the rewrite I changed the file name from `wp-bootstrap-navwalker.php` to `class-wp-bootstrap-navwalker.php` to better fit PHP Coding Standards naming conventions.

If you're using the master branch version of the walker try this as the require:
`require_once 'class-wp-bootstrap-navwalker.php';`

**Comment by baggarw1** [comment]
Hey @pattonwebz.  Just figured it out, for some reason I had a different version of the navwalker and thus causing the error.

Feel so stupid about this. Thanks for your help and prompt reply. 

Issue is closed.

**Comment by pattonwebz** [comment]
Not to worry, I only recently pushed the changed version with the new name. There may still be old documentation in the repo somewhere (if you ready the old require code here then I may have missed updating a reference to the new file, sorry!).

**Comment by baggarw1** [comment]
No man, all good your new docs seem good.

I was following a tutorial on how to implement it and the link in that was for some reason to another repo and not yours. 

As you can guess it had minor syntactical differences and my frustration grew on why it wasn't working, always thinking that my required file was the correct one.

Thanks a lot for your help and keep up the good work.

**Comment by artantme** [comment]
If you run into this mistake, please check if you are making a parent or child theme.
if it's child – use get_stylesheet_directory() instead of get_template_directory()

like this:

```

if ( ! file_exists( get_stylesheet_directory() . '/class-wp-bootstrap-navwalker.php' ) ) {
  // file does not exist... return an error.
  return new WP_Error( 'class-wp-bootstrap-navwalker-missing', __( 'It appears the class-wp-bootstrap-navwalker.php file may be missing.', 'wp-bootstrap-navwalker' ) );
} else {
  // file exists... require it.
  require_once get_stylesheet_directory() . '/class-wp-bootstrap-navwalker.php';
}
```

**Comment by dharashah251** [comment]
Hi all,@pattonwebz
I have write following code but getting error please give me solution
_**_function.php_**_

```
<?php 
//Register Nav claa_alias
 require_once('class-wp-bootstrap-navwalker.php');
 
 //Theme Support

 function wpb_theme_setup(){register_nav_menus(array('primary' => __('Primary Menu') ))}add_action('after_theme_setup','wpb_theme_setup');

```


_**_header.php_**_

```
 <nav class="navbar navbar-expand-md navbar-dark   bg-dark">
     <a class="navbar-brand" href="#">Carousel</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
     <?php
        wp_nav_menu( array(
            'theme_location'    => 'primary',
           'depth'             => 2,
             'container'         => 'div',
           'container_class'   => 'collapse navbar-collapse',
             'container_id'      => 'bs-example-navbar-collapse-1',
             'menu_class'        => 'nav navbar-nav',
             'fallback_cb'       => 'WP_Bootstrap_Navwalker::fallback',
             'walker'            => new WP_Bootstrap_Navwalker(),
             ));
         ?>
  
     </div>
   </nav>
```


**_ERROR_**

Fatal error
: Uncaught Error: Class 'WP_Bootstrap_Navwalker' not found in C:\xampp\htdocs\maple-leafe-foundation\wp-content\themes\hd bootstrap theme\header.php:53 Stack trace: #0 C:\xampp\htdocs\maple-leafe-foundation\wp-includes\template.php(722): require_once() #1 C:\xampp\htdocs\maple-leafe-foundation\wp-includes\template.php(671): load_template('C:\\xampp\\htdocs...', true) #2 C:\xampp\htdocs\maple-leafe-foundation\wp-includes\general-template.php(41): locate_template(Array, true) #3 C:\xampp\htdocs\maple-leafe-foundation\wp-content\themes\hd bootstrap theme\index.php(1): get_header() #4 C:\xampp\htdocs\maple-leafe-foundation\wp-includes\template-loader.php(78): include('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\maple-leafe-foundation\wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\maple-leafe-foundation\index.php(17): require('C:\\xampp\\htdocs...') #7 {main} thrown in
C:\xampp\htdocs\maple-leafe-foundation\wp-content\themes\hd bootstrap theme\header.php
on line
53

**Comment by pattonwebz** [comment]
@dharashah251 did you check out the comment above yours and test if that works for you. That code should help you identify if the class file is actually being included. Seems like it's not :s

**Comment by dharashah251** [comment]
@pattonwebz have tryied with code see below but error is same

**Function.php**

`<?php
//Register Nav claa_alias
if ( ! file_exists( get_stylesheet_directory() . '/class-wp-bootstrap-navwalker.php' ) ) {
    // file does not exist... return an error.
    return new WP_Error( 'class-wp-bootstrap-navwalker-missing', __( 'It appears the class-wp-bootstrap-navwalker.php file may be missing.', 'wp-bootstrap-navwalker' ) );
  } else {
    // file exists... require it.
    require_once get_stylesheet_directory() . '/class-wp-bootstrap-navwalker.php';
  };

//Theme Support

function wpb_theme_setup(){
    // Nav Menu
    register_nav_menus(array(
        'primary' => __('Primary Menu')
    ))
}

add_action('after_theme_setup','wpb_theme_setup');`

**ERROR**

Fatal error
: Uncaught Error: Class 'WP_Bootstrap_Navwalker' not found in C:\xampp\htdocs\maple-leafe-foundation\wp-content\themes\hd bootstrap theme\header.php:53 Stack trace: #0 C:\xampp\htdocs\maple-leafe-foundation\wp-includes\template.php(722): require_once() #1 C:\xampp\htdocs\maple-leafe-foundation\wp-includes\template.php(671): load_template('C:\\xampp\\htdocs...', true) #2 C:\xampp\htdocs\maple-leafe-foundation\wp-includes\general-template.php(41): locate_template(Array, true) #3 C:\xampp\htdocs\maple-leafe-foundation\wp-content\themes\hd bootstrap theme\index.php(1): get_header() #4 C:\xampp\htdocs\maple-leafe-foundation\wp-includes\template-loader.php(78): include('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\maple-leafe-foundation\wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\maple-leafe-foundation\index.php(17): require('C:\\xampp\\htdocs...') #7 {main} thrown in
C:\xampp\htdocs\maple-leafe-foundation\wp-content\themes\hd bootstrap theme\header.php
on line
53

**Comment by dharashah251** [comment]
Issue has shorted name mistake forgot to write s its"finctions.php" and i wrote "function.php"

Thanks for your help.
